### ISSUE TITLE
how does list-vcf handle homozygous reference

### ISSUE THREAD

**Issue by moe1619** [nickzren/atav#60]
Hi Nick,

In looking at output from --list-vcf, I noticed that ATAV will report homozygous reference for genotypes. In the original ticket to design the feature, you wrote the following...

`
Genotype:
Hom --> 1/1
Het --> 1/0
Hom Ref --> 0/0
NA --> ./.
`

I'm curious about Hom Ref. I though ATAV didn't store reference genotypes. When we do collapsing, we assume hom ref if DP > 10 but no variant. Is this the same? Or is ATAV actually storing hom ref for some sites? Also, in what circumstances would ATAV store NA? Does that mean there is dp < 10 for that site?

Thanks!

**Comment by nickzren** [comment]
Hi Josh,

The data pipeline has been developed to extract the Depth of Coverage (DP) from the VCF for all called variants (HOM/HET). Additionally, it extracts DP/coverage for all sites from the BAM file and then categorizes them into DP Bins using a run-length encoding method. Currently, the database categorizes these into only two DP Bins: > 10 or <= 10. Therefore, a valid HOM REF is indicated by a DP Bin > 10.  HOM REF NA means DP Bin <= 10.  (Note: it used DP Bin instead of DP for hom ref indication)

**Comment by moe1619** [comment]
Great. 

So it sounds like ATAV doesn't store hom ref (0/0) calls but if the site has DP >10 and no variant call, then it will output 0/0 when in --list-vcf. If DP < 10, it will output missing (./.) when you output list-vcf. Is that right?

Is that correct?

Thank you!

**Comment by nickzren** [comment]
Yes, correct.On Dec 6, 2023, at 6:33 AM, moe1619 ***@***.***> wrote:﻿
Great.
So it sounds like ATAV doesn't store hom ref (0/0) calls but if the site has DP >10 and no variant call, then it will output 0/0 when in --list-vcf. If DP < 10, it will output missing (./.) when you output list-vcf. Is that right?
Thank you!

**Comment by moe1619** [comment]
Thank you!
